### ISSUE TITLE
Multiple frontend applications

### ISSUE THREAD

**Issue by elfy941** [jbruinink/ng2boot#5]
Hello , if for example I want to use multiple frontend modules like a separate angular app for the client and one for the admin portal of the application. I've tried to add both as dependency to the backend module , when I start the application I can see in the console that both frontend module are built but when I go to the localhost:8080 it always opens the first one. 
My question is how would I be able to open the second angular application ?

**Comment by slegge** [comment]
When you open localhost:8080 it is opening 'index.html' by default, you'd have to make sure your two dependencies don't overlap either by mapping them differently in the resources section of your pom or changing page names

for example the easiest would be to map your admin static resources to a subdirectory:
```
<resources>
  <resource>
    <directory>target/frontend</directory>
    <targetPath>static/admin</targetPath>
  </resource>
</resources>
```

**Comment by elfy941** [comment]
I've added your mapping but still I can't load the second angular application. I try something like this to load the second app: 
`@RequestMapping(value = "/admin",produces = MediaType.TEXT_HTML_VALUE)
	public String test() {
		return "/admin/admin.html";
	}`
When I go to localhost:8080/admin , the admin.html page is loaded but the second angular components and styles are not loaded , the entire second application is not loaded , only the first page

**Comment by slegge** [comment]
I think you're getting confused between backend and frontend, you're creating a backend endpoint (/admin) that is just passing through the html for the page from the frontend.  You shouldn't need that mapping at all, if you take it out everything to localhost:8080/admin/**/* will bring up the frontend resources from the jar.

**Comment by elfy941** [comment]
Thanks for your help :) , in the end I managed to start the admin application .
Thanks again :+1:
